const fs = require('fs');

let file = fs.readFileSync('ntfs-img-kw-1.dd')
console.log("______________________________________________________________________________________")
console.log()
console.log(file.slice(3, 7).toString())
console.log("______________________________________________________________________________________")
console.log("Bytes Per Sector                 : " + file.slice(11, 13).toString('hex') + "")
console.log("Sectors Per Cluster              : " + file.slice(13, 14).toString('hex') + "")
console.log("Reserved Sectors                 : " + file.slice(14, 16).toString('hex') + "")
console.log("always 0                         : " + file.slice(16, 19).toString('hex') + "")
console.log("Media Descriptor                 : " + file.slice(21, 22).toString('hex') + "")
console.log("always 0                         : " + file.slice(22, 24).toString('hex') + "")
console.log("Sectors Per Track                : " + file.slice(24, 26).toString('hex') + "")
console.log("Number Of Heads                  : " + file.slice(26, 28).toString('hex') + "")
console.log("Hidden Sectors                   : " + file.slice(28, 32).toString('hex') + "")
console.log("Total Sectors                    : " + file.slice(40, 48).toString('hex') + "")
console.log("Clusters Per File Record Segment : " + file.slice(64, 68).toString('hex') + "")
console.log("Clusters Per Index Buffer        : " + file.slice(68, 69).toString('hex') + "")
console.log("Volume Serial Number             : " + file.slice(72, 80).toString('hex') + "")
console.log("Checksum                         : " + file.slice(80, 84).toString('hex') + "")
console.log("______________________________________________________________________________________")
